version: "3.9"

services:
  database:
    container_name: gamera-db
    image: postgres:14.2-alpine
    volumes:
      - postgresql_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=gamera
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin

volumes:
  postgresql_data: {}