server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/gamera
    username: postgres
    password: admin

  jpa:
    database: postgresql
    properties:
      hibernate:
        default_schema: forum
        jdbc:
          time_zone: UTC